[template]
src = "nginx.tmpl"
dest = "/etc/nginx/nginx.conf"
owner = "nginx"
mode = "0644"
keys = [ 
	"/services" 
]
reload_cmd = "echo -e \"POST /containers/nginx/kill?signal=HUP HTTP/1.0\r\n\" | nc -U /var/run/docker.sock"